const FETCH_ROOM_REQUEST = 'roomDetectors/FetchRoomRequest';
const FETCH_ROOM_SUCCESS = 'roomDetectors/FetchRoomSuccess';
const FETCH_ROOM_CANCELLED = 'roomDetectors/FetchRoomCancelled';
const FETCH_ROOM_ERROR = 'roomDetectors/FetchRoomError';

const START_ROOM_TRACKING = 'roomDetectors/START_ROOM_TRACKING';
const STOP_ROOM_TRACKING = 'roomDetectors/STOP_ROOM_TRACKING';

const CREATE_NEW_ROOM_DETECTOR_REQUEST = 'roomDetectors/CREATE_NEW_ROOM_DETECTOR_REQUEST';
const CREATE_NEW_ROOM_DETECTOR_SUCCESS = 'roomDetectors/CREATE_NEW_ROOM_DETECTOR_SUCCESS';
const STOP_ALL_ROOM_DETECTORS = 'roomDetectors/STOP_ALL_ROOM_DETECTORS';

export {
  FETCH_ROOM_CANCELLED,
  FETCH_ROOM_ERROR,
  FETCH_ROOM_REQUEST,
  FETCH_ROOM_SUCCESS,

  START_ROOM_TRACKING,
  STOP_ROOM_TRACKING,

  CREATE_NEW_ROOM_DETECTOR_REQUEST,
  CREATE_NEW_ROOM_DETECTOR_SUCCESS,
  STOP_ALL_ROOM_DETECTORS,
}
